---
title: " FLASH - analyis - CorShrink matrix "
author: "Kushal K Dey"
date: "5/17/2017"
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

In this script, we check for the performance of FLASH on the CorShrink matrix.

```{r}
data <- get(load("../output/ash_cor_only_voom_pearson_gtex_tissues.rda"))

gene_names <- as.character(read.table(file = "../data/GTEX_V6/gene_names_GTEX_V6.txt")[,1])
gene_names_1 <- as.character(sapply(gene_names, function(x) return(strsplit(x, "[.]")[[1]][1])))
 
person_label=read.table("../data/GTEX_V6/person_identifier_labels_with_numbers.txt");
samples_id <- read.table(file = "../data/GTEX_V6/samples_id.txt")[,1]

samples_person <- sapply(samples_id, function(x) return(paste0(strsplit(as.character(x), "-")[[1]][1:2], collapse ="-")))
tissue_labels <- read.table(file = "../data/GTEX_V6/samples_id.txt")[,3]

unique_persons <- unique(samples_person)
unique_tissues <- unique(tissue_labels)
```

```{r echo=FALSE, eval=TRUE}
order_index <- c();
U <- unique_tissues
order_index <- c(order_index, grep("Brain", U))
order_index <- c(order_index, grep("fibroblast", U))
order_index <- c(order_index, grep("EBV", U))
order_index <- c(order_index, grep("Spleen", U))
order_index <- c(order_index, grep("Whole Blood", U))
order_index <- c(order_index, grep("Muscle - Skeletal", U))
order_index <- c(order_index, grep("Liver", U))
order_index <- c(order_index, grep("Pancreas", U))
order_index <- c(order_index, grep("Stomach", U))
order_index <- c(order_index, grep("Kidney - Cortex", U))
order_index <- c(order_index, grep("Adrenal Gland", U))
order_index <- c(order_index, grep("Colon - Transverse", U))
order_index <- c(order_index, grep("Small Intestine - Terminal Ileum", U))
order_index <- c(order_index, grep("Heart - Atrial Appendage", U))
order_index <- c(order_index, grep("Heart - Left Ventricle", U))
order_index <- c(order_index, grep("Minor Salivary Gland", U))
order_index <- c(order_index, grep("Skin - Sun Exposed", U))
order_index <- c(order_index, grep("Skin - Not Sun Exposed", U))
order_index <- c(order_index, grep("Lung", U))
order_index <- c(order_index, grep("Ovary", U))
order_index <- c(order_index, grep("Thyroid", U))
order_index <- c(order_index, grep("Pituitary", U))
order_index <- c(order_index, grep("Testis", U))
order_index <- c(order_index, grep("Nerve - Tibial", U))
order_index <- c(order_index, grep("Breast - Mammary Tissue", U))
order_index <- c(order_index, grep("Adipose - Visceral", U))
order_index <- c(order_index, grep("Adipose - Subcutaneous", U))
order_index <- c(order_index, grep("Artery - Coronary", U))
order_index <- c(order_index, grep("Artery - Tibial", U))
order_index <- c(order_index, grep("Artery - Aorta", U))
order_index <- c(order_index, grep("Esophagus - Mucosa", U))
order_index <- c(order_index, grep("Vagina", U))
order_index <- c(order_index, grep("Cervix - Endocervix", U))
order_index <- c(order_index, grep("Esophagus - Gastroesophageal Junction", U))
order_index <- c(order_index, grep("Colon - Sigmoid", U))
order_index <- c(order_index, grep("Esophagus - Muscularis", U))
order_index <- c(order_index, grep("Cervix - Ectocervix", U))
order_index <- c(order_index, grep("Fallopian", U))
order_index <- c(order_index, grep("Prostate", U))
order_index <- c(order_index, grep("Uterus", U))
order_index <- c(order_index, grep("Bladder", U))
```


```{r}
flash_out <-  get(load("../output/backfit_flash_output_corshrink_15.rda"))

corr_mat_vectors_facs <- flash_out$l
corr_mat_vectors_facs_trans <- (exp(2*corr_mat_vectors_facs)-1)/(exp(2*corr_mat_vectors_facs)+1)
```


```{r}
corr_mat_fac <- array(0, c(dim(data)[1], dim(data)[2], 20));

for(k in 1:dim(corr_mat_vectors_facs)[2]){
  mat2 <- matrix(0, dim(data)[1], dim(data)[2])
  mat2[lower.tri(mat2)] <- corr_mat_vectors_facs_trans[,k]
  diag(mat2) <- 1
  corr_mat_fac[,,k] <- (mat2 + t(mat2))
}

for(num in 1:dim(corr_mat_vectors_facs)[2]){
      temp_mat <- as.matrix(corr_mat_fac[order_index,order_index, num])
      min_temp <- quantile(temp_mat[lower.tri(temp_mat)], 0.1)
      max_temp <- quantile(temp_mat[lower.tri(temp_mat)], 0.9)
      temp_mat[temp_mat > max_temp] = max_temp
      temp_mat[temp_mat < min_temp] = min_temp
      col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(temp_mat,
          col=col, main=paste0("corr structure factor: ", num), cex.main=2,
          xaxt = "n", yaxt = "n", zlim=c(min_temp,max_temp))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
}

```

Okay now we look at genes that turned to be enriched in driving these factors.

```{r echo=FALSE, eval=FALSE}
abs_effect <- exp(flash_out$f)
normalized_abs_effect <- apply(abs_effect, 2, function(x) return (x/sum(x)))
features <- CountClust::ExtractTopFeatures(normalized_abs_effect, top_features = 10, method = "poisson", options = "min")

```

```{r echo=FALSE, eval=FALSE}
k <- 4
num <- 3

col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index, features[k,num]],
          col=col, main=paste0("corr structure: ", gene_names_1[features[k,num]]), cex.main=2,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```
```{r}
projected_flash_data <- (flash_out$l)%*%t(flash_out$f)
inv_projected_flash_data <- (exp(2*projected_flash_data)-1)/(exp(2*projected_flash_data)+1)
```

Create a projected FLASH adjusted correlation matrix.

```{r}
projected_data <- array(0, c(dim(data)[1], dim(data)[2], dim(data)[3]));

for(ll in 1:dim(data)[3]){
  mat2 <- matrix(0, dim(data)[1], dim(data)[2])
  mat2[lower.tri(mat2)] <- inv_projected_flash_data[,ll]
  projected_data[,,ll] <- (mat2 + t(mat2))
  diag(projected_data[,,ll]) <- 1
}

```


```{r}
par(mfrow=c(1,2))
num <- grep("ENSG00000244734", gene_names_1)
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(projected_data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```



```{r}
par(mfrow=c(1,2))
num <- grep("ENSG00000171401", gene_names_1)
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(projected_data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```

```{r}
par(mfrow=c(1,2))
num <- grep("ENSG00000170477", gene_names_1)
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(projected_data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```

```{r}
par(mfrow=c(1,2))
num <- grep("ENSG00000133392", gene_names_1)
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(projected_data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```

```{r}
par(mfrow=c(1,2))
num <- grep("ENSG00000133392", gene_names_1)
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    
col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
          rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
    image(projected_data[order_index, order_index,num],
          col=col, main=paste0("corr structure: ", gene_names_1[num]), cex.main=0.7,
          xaxt = "n", yaxt = "n", zlim=c(-1,+1))
    axis(1, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
    axis(2, at = seq(0, 1, length.out = 53), labels = unique_tissues[order_index], las=2, cex.axis = 0.5)
```

```{r}
num <- grep("ENSG00000133392", gene_names_1)
flash_out$f[num,]
```

```{r}
num <- grep("ENSG00000170477", gene_names_1)
flash_out$f[num,]
```

```{r}
num <- grep("ENSG00000171401", gene_names_1)
flash_out$f[num,]
```

```{r}
num <- grep("ENSG00000244734", gene_names_1)
flash_out$f[num,]
```

## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
