---
title: "GTEx clusters vs genewide CorShrink"
author: "Kushal K Dey"
date: "5/28/2017"
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

How do the genes from the GTEx clusters obtained through CountClust look like in terms of CorShrink
output.

```{r}
cor_result <- get(load("../output/genewide_ash_out_tissue_mat.rda"))
common_samples <- get(load("../output/common_samples.rda"))
tissue_labels <- read.table(file = "../data/GTEX_V6/samples_id.txt")[,3]

#library(data.table)
#data <- data.frame(fread("../data/GTEX_V6/cis_gene_expression.txt"))
#matdata <- t(data[,-c(1,2)])

gene_names <- as.character(read.table(file = "../data/GTEX_V6/gene_names_GTEX_V6.txt")[,1])
gene_names_1 <- as.character(sapply(gene_names, function(x) return(strsplit(x, "[.]")[[1]][1])))


U <- unique(tissue_labels)
```

```{r echo=FALSE, eval=TRUE}
order_index <- c();
order_index <- c(order_index, grep("Brain", U))
order_index <- c(order_index, grep("fibroblast", U))
order_index <- c(order_index, grep("EBV", U))
order_index <- c(order_index, grep("Spleen", U))
order_index <- c(order_index, grep("Whole Blood", U))
order_index <- c(order_index, grep("Muscle - Skeletal", U))
order_index <- c(order_index, grep("Liver", U))
order_index <- c(order_index, grep("Pancreas", U))
order_index <- c(order_index, grep("Stomach", U))
order_index <- c(order_index, grep("Kidney - Cortex", U))
order_index <- c(order_index, grep("Adrenal Gland", U))
order_index <- c(order_index, grep("Colon - Transverse", U))
order_index <- c(order_index, grep("Small Intestine - Terminal Ileum", U))
order_index <- c(order_index, grep("Heart - Atrial Appendage", U))
order_index <- c(order_index, grep("Heart - Left Ventricle", U))
order_index <- c(order_index, grep("Minor Salivary Gland", U))
order_index <- c(order_index, grep("Skin - Sun Exposed", U))
order_index <- c(order_index, grep("Skin - Not Sun Exposed", U))
order_index <- c(order_index, grep("Lung", U))
order_index <- c(order_index, grep("Ovary", U))
order_index <- c(order_index, grep("Thyroid", U))
order_index <- c(order_index, grep("Pituitary", U))
order_index <- c(order_index, grep("Testis", U))
order_index <- c(order_index, grep("Nerve - Tibial", U))
order_index <- c(order_index, grep("Breast - Mammary Tissue", U))
order_index <- c(order_index, grep("Adipose - Visceral", U))
order_index <- c(order_index, grep("Adipose - Subcutaneous", U))
order_index <- c(order_index, grep("Artery - Coronary", U))
order_index <- c(order_index, grep("Artery - Tibial", U))
order_index <- c(order_index, grep("Artery - Aorta", U))
order_index <- c(order_index, grep("Esophagus - Mucosa", U))
order_index <- c(order_index, grep("Vagina", U))
order_index <- c(order_index, grep("Cervix - Endocervix", U))
order_index <- c(order_index, grep("Esophagus - Gastroesophageal Junction", U))
order_index <- c(order_index, grep("Colon - Sigmoid", U))
order_index <- c(order_index, grep("Esophagus - Muscularis", U))
order_index <- c(order_index, grep("Cervix - Ectocervix", U))
order_index <- c(order_index, grep("Fallopian", U))
order_index <- c(order_index, grep("Prostate", U))
order_index <- c(order_index, grep("Uterus", U))
order_index <- c(order_index, grep("Bladder", U))
```

```{r}
library(CorShrink)
source("../../CorShrink/R/CorShrinkML.R")
```


## Whole body clusters vs CorShrink

```{r fig.width = 15, fig.height = 8}

for(k in 1:20){
      genes <- as.character(read.table(paste0("../utilities/gene_names_clus_", k, ".txt"))[1:6,1])
    par(mfrow=c(2,3))
    
    for(l in 1:length(genes)){
      col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
            rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
      image(as.matrix(cor_result[order_index,order_index,grep(paste0(genes[l]),gene_names_1)]),
            col=col, main=paste0("corshrink: ", genes[l]), cex.main=2,
            xaxt = "n", yaxt = "n", zlim=c(-1,1))
      axis(1, at = seq(0, 1, length.out = ncol(cor_result[,,1])), labels = U[order_index], las=2, cex.axis = 0.5)
      axis(2, at = seq(0, 1, length.out = ncol(cor_result[,,1])), labels = U[order_index], las=2, cex.axis = 0.5)
    }
}

```


## Brain clusters vs CorShrink

```{r fig.width = 13, fig.height = 8}

for(k in 1:6){
  genes <- as.character(read.table(paste0("../utilities/gene_names_brain_clus_", k, ".txt"))[1:6,1])
 par(mfrow=c(2,3))

 for(l in 1:length(genes)){
   col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
         rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
   image(as.matrix(cor_result[order_index[1:13],order_index[1:13],grep(paste0(genes[l]),gene_names_1)]),
         col=col, main=paste0("corshrink: ", genes[l]), cex.main=2,
         xaxt = "n", yaxt = "n", zlim=c(-1,1))
   axis(1, at = seq(0, 1, length.out = 13), labels = U[order_index[1:13]], las=2, cex.axis = 1)
   axis(2, at = seq(0, 1, length.out = 13), labels = U[order_index[1:13]], las=2, cex.axis = 1)
 }
}
 
```


## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
