---
title: "MASH on systemic bmi study (canonical)"
author: "Kushal K Dey"
date: "6/18/2017"
output: html_document
---

```{r}
library(mashr)
```

```{r}
data <- get(load("../output/bmi_cor_nonmash.rda"))
betahat <- data$betahat
sebetahat <- data$sebetahat
zdat <- betahat/sebetahat
```

```{r}
common_samples <- get(load("../output/common_samples.rda"))
tissue_labels <- read.table(file = "../data/GTEX_V6/samples_id.txt")[,3]

gene_names <- as.character(read.table(file = "../data/GTEX_V6/gene_names_GTEX_V6.txt")[,1])
gene_names_1 <- as.character(sapply(gene_names, function(x) return(strsplit(x, "[.]")[[1]][1])))

U <- unique(tissue_labels)
```


```{r}
mash_dat <- get(load("../output/mash_bmi_canonical.rda"))
```

```{r}
barplot(get_estimated_pi(mash_dat), las = 2, cex.names = 0.3)
```

```{r}
U[c(1, 2, 8, 24, 25, 31, 53)]
```
Cervix and Fallopian tube have small number of samples which are likely driving this. We focus on Whole Blood first.

## Blood specific genes

```{r}
blood_specific <- apply(mash_dat$result$lfdr, 1, function(x) {
      if(x[53] < 0.05 && min(x[-53])> 0.6){
        return(1)
      }else{
        return(0)
      }
})
```

```{r}
length(which(blood_specific==1))
```

```{r}
imp_genes <- gene_names_1[which(blood_specific==1)]
imp_genes[1:10]
```

```{r}
write.table(imp_genes, file = "../utilities/bmi_mash/blood.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
pathway2 <- read.delim("../utilities/bmi_mash/blood_pathway.tab")
if(length(which(pathway2$q.value < 0.05)) > 2){
  pathway2 <- pathway2[which(pathway2$q.value < 0.05),]
}
maxpath = 75
pathway <- pathway2[1:min(maxpath, dim(pathway2)[1]), ]
ensembl_genes <- pathway$members_input_overlap
pathway_list_genes <- sapply(ensembl_genes, function(x) return(strsplit(as.character(x), "; ")))
all_genes <- Reduce(union, pathway_list_genes)
pathway_mat <- matrix(0, length(pathway_list_genes), length(all_genes))
for(l in 1:dim(pathway_mat)[1]){
  pathway_mat[l, match(pathway_list_genes[[l]], all_genes)] <- 1
}

pathway_bimat <- (pathway_mat)%*%t(pathway_mat)
pathway_bimat_prop <- diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1]) %*% pathway_bimat %*% diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1])

col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
heatmap(pathway_bimat_prop, labRow = pathway$pathway, labCol = pathway$pathway, cexRow = 0.3, cexCol = 0.3, col = col, zlim = c(-1,1),
        scale = "none", margins = c(5, 5))
```


## Adipose specific genes

```{r}
adipose_specific <- apply(mash_dat$result$lfdr, 1, function(x) {
      if(x[1] < 0.05 && median(x[-1])> 0.5){
        return(1)
      }else{
        return(0)
      }
})
```

```{r}
length(which(adipose_specific==1))
```

```{r}
imp_genes <- gene_names_1[which(adipose_specific==1)]
imp_genes[1:10]
```

```{r}
write.table(imp_genes, file = "../utilities/bmi_mash/adipose.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
pathway2 <- read.delim("../utilities/bmi_mash/adipose_pathway.tab")
if(length(which(pathway2$q.value < 0.05)) > 2){
  pathway2 <- pathway2[which(pathway2$q.value < 0.05),]
}
maxpath = 75
pathway <- pathway2[1:min(maxpath, dim(pathway2)[1]), ]
ensembl_genes <- pathway$members_input_overlap
pathway_list_genes <- sapply(ensembl_genes, function(x) return(strsplit(as.character(x), "; ")))
all_genes <- Reduce(union, pathway_list_genes)
pathway_mat <- matrix(0, length(pathway_list_genes), length(all_genes))
for(l in 1:dim(pathway_mat)[1]){
  pathway_mat[l, match(pathway_list_genes[[l]], all_genes)] <- 1
}

pathway_bimat <- (pathway_mat)%*%t(pathway_mat)
pathway_bimat_prop <- diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1]) %*% pathway_bimat %*% diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1])

col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
heatmap(pathway_bimat_prop, labRow = pathway$pathway, labCol = pathway$pathway, cexRow = 0.3, cexCol = 0.3, col = col, zlim = c(-1,1),
        scale = "none", margins = c(5, 5))
```

## Amygdala specific genes

```{r}
amygdala_specific <- apply(mash_dat$result$lfdr, 1, function(x) {
      if(x[8] < 0.05 && median(x[-8])> 0.6){
        return(1)
      }else{
        return(0)
      }
})
```

```{r}
length(which(amygdala_specific==1))
```

```{r}
imp_genes <- gene_names_1[which(amygdala_specific==1)]
imp_genes[1:10]
```

```{r}
write.table(imp_genes, file = "../utilities/bmi_mash/amygdala.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

No enrichment observed.


## Shared  genes

```{r}
num_lfsr_below_thresh <- apply(mash_dat$result$lfdr, 1, function(x) return(length(which(x < 0.05))))

imp_indices <- which(num_lfsr_below_thresh == 53)
imp_genes <- gene_names_1[imp_indices]
length(imp_genes)
imp_genes[1:10]
```

```{r}
write.table(imp_genes, file = "../utilities/bmi_mash/all.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
pathway2 <- read.delim("../utilities/bmi_mash/all_pathway.tab")
if(length(which(pathway2$q.value < 0.05)) > 2){
  pathway2 <- pathway2[which(pathway2$q.value < 0.05),]
}
maxpath = 75
pathway <- pathway2[1:min(maxpath, dim(pathway2)[1]), ]
ensembl_genes <- pathway$members_input_overlap
pathway_list_genes <- sapply(ensembl_genes, function(x) return(strsplit(as.character(x), "; ")))
all_genes <- Reduce(union, pathway_list_genes)
pathway_mat <- matrix(0, length(pathway_list_genes), length(all_genes))
for(l in 1:dim(pathway_mat)[1]){
  pathway_mat[l, match(pathway_list_genes[[l]], all_genes)] <- 1
}

pathway_bimat <- (pathway_mat)%*%t(pathway_mat)
pathway_bimat_prop <- diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1]) %*% pathway_bimat %*% diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1])

col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
heatmap(pathway_bimat_prop, labRow = pathway$pathway, labCol = pathway$pathway, cexRow = 0.3, cexCol = 0.3, col = col, zlim = c(-1,1),
        scale = "none", margins = c(5, 5))
```



```{r}
num_lfsr_below_thresh <- apply(mash_dat$result$lfdr, 1, function(x) return(length(which(x < 0.05))))

imp_indices <- which(num_lfsr_below_thresh > 25)
imp_genes <- gene_names_1[imp_indices]
length(imp_genes)
imp_genes[1:10]
```

```{r}
write.table(imp_genes, file = "../utilities/bmi_mash/half.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
pathway2 <- read.delim("../utilities/bmi_mash/half_pathway.tab")
if(length(which(pathway2$q.value < 0.05)) > 2){
  pathway2 <- pathway2[which(pathway2$q.value < 0.05),]
}
maxpath = 75
pathway <- pathway2[1:min(maxpath, dim(pathway2)[1]), ]
ensembl_genes <- pathway$members_input_overlap
pathway_list_genes <- sapply(ensembl_genes, function(x) return(strsplit(as.character(x), "; ")))
all_genes <- Reduce(union, pathway_list_genes)
pathway_mat <- matrix(0, length(pathway_list_genes), length(all_genes))
for(l in 1:dim(pathway_mat)[1]){
  pathway_mat[l, match(pathway_list_genes[[l]], all_genes)] <- 1
}

pathway_bimat <- (pathway_mat)%*%t(pathway_mat)
pathway_bimat_prop <- diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1]) %*% pathway_bimat %*% diag(1/sqrt(diag(pathway_bimat)), dim(pathway_bimat)[1])

col=c(rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)))
heatmap(pathway_bimat_prop, labRow = pathway$pathway, labCol = pathway$pathway, cexRow = 0.3, cexCol = 0.3, col = col, zlim = c(-1,1),
        scale = "none", margins = c(5, 5))
```

## Reads expression profiling 

Here we do an expression profiling of some of the important genes we obtained from above

```{r}
person_tissue_genes <- get(load("../output/person_tissue_genes_voom.rda"))
sample_attributes <- get(load("../output/sample_attributes_filtered.rda"))
```

```{r}
betahat_sebetahat_2 <- get(load("../output/bmi_cor_nonmash.rda"))
tmat <- betahat_sebetahat_2$betahat/betahat_sebetahat_2$sebetahat
```

### ENSG00000000457

```{r}
indices <- match("ENSG00000000457", gene_names_1)
```

```{r}
plot(1:53, tmat[,indices], type = "b", xlab = "tissues", ylab="t scores")
text(1:53, tmat[,indices], U, cex=0.3)
```

```{r}
par(new=TRUE)
par(mfrow = c(3,3))
for(j in 1:53){
  temp1 <- person_tissue_genes[,j,indices]
  plot(sample_attributes$BMI, temp1, ylab = dimnames(person_tissue_genes)[[2]][j])
  lines(loess.smooth(sample_attributes$BMI, temp1, family = "gaussian"), 
        col="red", lty=2, lwd=2)
}
```


### ENSG00000000971

```{r}
indices <- match("ENSG00000000971", gene_names_1)
```

```{r}
plot(1:53, tmat[,indices], type = "b", xlab = "tissues", ylab="t scores")
text(1:53, tmat[,indices], U, cex=0.3)
```

```{r}
par(new=TRUE)
par(mfrow = c(3,3))
for(j in 1:53){
  temp1 <- person_tissue_genes[,j,indices]
  plot(sample_attributes$BMI, temp1, ylab = dimnames(person_tissue_genes)[[2]][j])
  lines(loess.smooth(sample_attributes$BMI, temp1, family = "gaussian"), 
        col="red", lty=2, lwd=2)
}
```

### ENSG00000037757

```{r}
indices <- match("ENSG00000037757", gene_names_1)
```

```{r}
plot(1:53, tmat[,indices], type = "b", xlab = "tissues", ylab="t scores")
text(1:53, tmat[,indices], U, cex=0.3)
```

```{r}
par(new=TRUE)
par(mfrow = c(3,3))
for(j in 1:53){
  temp1 <- person_tissue_genes[,j,indices]
  plot(sample_attributes$BMI, temp1, ylab = dimnames(person_tissue_genes)[[2]][j])
  lines(loess.smooth(sample_attributes$BMI, temp1, family = "gaussian"), 
        col="red", lty=2, lwd=2)
}
```

### ENSG00000001036

```{r}
indices <- match("ENSG00000001036", gene_names_1)
```

```{r}
plot(1:53, tmat[,indices], type = "b", xlab = "tissues", ylab="t scores")
text(1:53, tmat[,indices], U, cex=0.3)
```

```{r}
par(new=TRUE)
par(mfrow = c(3,3))
for(j in 1:53){
  temp1 <- person_tissue_genes[,j,indices]
  plot(sample_attributes$BMI, temp1, ylab = dimnames(person_tissue_genes)[[2]][j])
  lines(loess.smooth(sample_attributes$BMI, temp1, family = "gaussian"), 
        col="red", lty=2, lwd=2)
}
```
